### ISSUE TITLE
9. Bits, bytes, kilobytes (KB), megabytes (MB), gigabytes (GB), terabytes (TB)

### ISSUE THREAD

**Issue by SHJordan** [SHJordan/U3C3O12T#9]

**Comment by SHJordan** [comment]
![Image](https://github.com/user-attachments/assets/3e2cdbe9-3d71-4270-9c58-3cc2b78fb342)
Enquanto ele não faz o PR. Só pra documentar.

**Comment by PedroVentura21** [comment]
Por um breve momento ia fazendo usando as equivalências por potência de 2, depois vi que seria em potência de 10, mas agora estou em dúvida qual dos dois seriam...
Por fim, o request que mandei está em potência de 10.
